### ISSUE TITLE
Issue with additem menu and Soul

### ISSUE THREAD

**Issue by Xellon100** [Vermunds/SkyrimSoulsRE#2]
Thanks for the update. It seems when I use additem menu and select an outfit of my choice, it doesn't want to open up the next menu sometimes.

Its random. Sometimes it works, sometimes it doesn't while I'm running hook and soul. Using ur latest ver with 1.5.8.0

**Comment by Vermunds** [comment]
In the meantime you can set bCustomMenu to 0 to fix it. Obviously, it will make those menus paused.

**Comment by Vermunds** [comment]
There is now an optional patch available for UIExtensions on the Nexus page that should fix this.
